# Generated by Django 4.1.1 on 2022-09-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=2000)),
                ('date_added', models.DateField()),
                ('author', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('kids', models.BooleanField()),
                ('from_hn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parent_id', models.BigIntegerField()),
                ('author', models.CharField(max_length=200)),
                ('date_added', models.DateField()),
                ('kids', models.BooleanField()),
                ('text', models.CharField(max_length=2000)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hackernews.stories')),
            ],
        ),
    ]
