# Generated by Django 4.1.1 on 2022-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stories',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='stories',
            name='story_type',
            field=models.CharField(default='story', max_length=20),
        ),
    ]
