# Generated by Django 4.1.1 on 2022-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0002_alter_stories_options_stories_story_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stories',
            name='kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stories',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
