# Generated by Django 4.1.1 on 2022-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackernews', '0003_alter_comments_kids_alter_stories_kids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stories',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
